language: node_js
node_js:
- node
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
  - npm install
  - make build
deploy:
  skip_cleanup: true
  provider: s3
  local_dir: dist
  bucket: "english-number.com"
  region: ap-southeast-2
  secret_access_key:
    secure: X97dXMNnDoCw89a+AO/WfUJGApYAkCSefHMabb9QziPw7qZ6bBBZN/uAtmQxaO2c9i3GqBap1aOXs7HnuRgTZz4evTi2w1Ht/bDUzTZbicBsXAtAz1EGr3gKsXGB5IQuIAZQewS6J1n4bHhAUsF6KCjQoBv7/+GMaCwCfiSGJ6n6LJoLvshW0Pf0OTkz2kt4UF9gxmXWC80+N/S5uyaC3HyF26I6Vlna2o4i5muo0k5GobAO1k/KFmMlnMfLiElboQXRxUA4LOcv3TYKgbFbBmFwP02rr8slg287xWD6fWao20vKjPbkMQkmDPTB8FB8j/H9b0/judX0HJZDW4JviL0IVGcjc/YJFmHmnRs6U6W8d6cAOaYWJ7CY52IRQYUmQUqN3Qz1abMVw9FAfwzgEmxiUle8LZX/OqCJwarMLSNw+dgmOYJByf7mx6JydLV3NALuAhWKzTWdSmF2tKfrqSryPinOz0oaXDM4w9zDTNtwevFckeCLv/ODAXyxZ1QHMyFwk1e3sEzF/zFTIg8DDhWeQH24hhLuAfp1b4i+9sfnfVc3fRqyVKh2ceWVEIYbH5or7IsJBEUYsYonqI85f6GPemix+c9fyPknOaT2r0V61aHV06rLViJltkU3lHyFIXSpxhHFsJY5nvhI911vcd7VB/D5OFbivF5ee+44Zx4=
  access_key_id:
    secure: qe1AN2ceGMyarnB4OOiXDQD08QL9AbjXA+0nyxpSjgEAzzQ+oJ4LjdHXEPK6l1aFlf3wZ0Y4fkdmEV11JapySRmhrqGf53n4Ml/Dcd3V7D8AuAS60LN7A0VxAwFBFiEtiDg/QMuv64eBwmcaRlALfW+MTIIKmO18SY5UDWsWpk1LWjfJvO7JGO98l1qryidDXtC+OaQUIaQJkCsVhqXDuBTAWZTCQJp4sj50JMOW4UpNC0bv3t93d7lwwf8BUk5mFgD5J+Vsj54d3/XKveJ1h8TzasI9S+qhNQHsFRPIbSOTnG8LJyq++jUy+1bJLFJDwavKh1Fzr1nAlSfiDT4PPti7Bgqe4kzSZEzKF5hBziM5dtCwyYC2xLAo0UsOntWthNLylTajEL9OPCCQHOjX2DvWygXaYHmVbtqGWWADtsKCxykFqmHy8tiSQQgovy1lVVk5oHv1IEM/w2NFpsKsHdqoOItdFecoY3098mbT1gWYsVp79NzWpWihIbGG64VnGXhlrbuxMHyKd0hXfct93biD+LtyqCW/f82KSitw0AWGhs4sLL5vMr5bTYmvlIijdy8LdaF02bWqkLZFLqK1BZMc4IT0ExhlBGVitoGqpHSYp57pvOqAzzbvK5xXqcz7upNRfJovjx5Kc7KJ3u+nqBOpOHGODp4lsa7shtdND9U=
